[package]
name = "mcp-host"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
bytes = "1"
clap = { version = "4.6.0", features = ["derive"] }
directories = "6"
fs2 = "0.4"
futures-util = { version = "0.3", features = ["sink"] }
interprocess = { version = "=2.4.2", features = ["tokio"] }
mcp-host-core = { version = "0.1.1", path = "../mcp-host-core" }
mcp-host-mcp = { version = "0.1.1", path = "../mcp-host-mcp" }
rmcp = "=2.2.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "io-util", "sync", "time", "signal", "fs", "io-std", "process"] }
tokio-util = { version = "0.7", features = ["codec", "rt"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

[lints]
workspace = true

[dev-dependencies]
tempfile = "3"
